import XCTest
@testable import Sashimi

final class DeepLinkTests: XCTestCase {

    // MARK: - Valid URLs (as generated by TopShelf/ContentProvider)

    func testParsePlayURL() {
        let link = DeepLink(url: URL(string: "sashimi://play/abc123")!)
        XCTAssertEqual(link?.action, .play)
        XCTAssertEqual(link?.itemId, "abc123")
    }

    func testParseItemURL() {
        let link = DeepLink(url: URL(string: "sashimi://item/f4c8e9d2a1b3")!)
        XCTAssertEqual(link?.action, .item)
        XCTAssertEqual(link?.itemId, "f4c8e9d2a1b3")
    }

    func testSchemeAndHostAreCaseInsensitive() {
        let link = DeepLink(url: URL(string: "SASHIMI://Play/abc123")!)
        XCTAssertEqual(link?.action, .play)
        XCTAssertEqual(link?.itemId, "abc123")
    }

    func testTrailingSlashIsIgnored() {
        let link = DeepLink(url: URL(string: "sashimi://item/abc123/")!)
        XCTAssertEqual(link?.action, .item)
        XCTAssertEqual(link?.itemId, "abc123")
    }

    func testExtraPathComponentsUseFirstAsItemId() {
        let link = DeepLink(url: URL(string: "sashimi://play/abc123/extra")!)
        XCTAssertEqual(link?.action, .play)
        XCTAssertEqual(link?.itemId, "abc123")
    }

    // MARK: - Malformed URLs (must be rejected, never crash)

    func testRejectsWrongScheme() {
        XCTAssertNil(DeepLink(url: URL(string: "https://play/abc123")!))
        XCTAssertNil(DeepLink(url: URL(string: "sashimii://play/abc123")!))
    }

    func testRejectsUnknownAction() {
        XCTAssertNil(DeepLink(url: URL(string: "sashimi://delete/abc123")!))
        XCTAssertNil(DeepLink(url: URL(string: "sashimi://playitem/abc123")!))
    }

    func testRejectsMissingItemId() {
        XCTAssertNil(DeepLink(url: URL(string: "sashimi://play")!))
        XCTAssertNil(DeepLink(url: URL(string: "sashimi://play/")!))
        XCTAssertNil(DeepLink(url: URL(string: "sashimi://item")!))
    }

    func testRejectsMissingHost() {
        XCTAssertNil(DeepLink(url: URL(string: "sashimi:///abc123")!))
        XCTAssertNil(DeepLink(url: URL(string: "sashimi:")!))
    }

    // MARK: - DeepLinkDestination identity

    private func makeItem(id: String) -> BaseItemDto {
        BaseItemDto(
            id: id, name: "Test", type: .movie,
            seriesName: nil, seriesId: nil, seasonId: nil, parentId: nil,
            indexNumber: nil, parentIndexNumber: nil, overview: nil,
            runTimeTicks: nil, userData: nil, imageTags: nil,
            backdropImageTags: nil, parentBackdropImageTags: nil,
            primaryImageAspectRatio: nil, mediaType: nil, productionYear: nil,
            communityRating: nil, officialRating: nil, genres: nil,
            taglines: nil, people: nil, criticRating: nil,
            premiereDate: nil, chapters: nil, path: nil, remoteTrailers: nil, mediaStreams: nil
        )
    }

    func testDestinationIdDiffersByAction() {
        // Same item, different action must change identity so the
        // fullScreenCover re-presents instead of mutating in place.
        let item = makeItem(id: "abc123")
        XCTAssertNotEqual(DeepLinkDestination.play(item).id, DeepLinkDestination.detail(item).id)
    }

    func testDestinationIdDiffersByItem() {
        XCTAssertNotEqual(
            DeepLinkDestination.play(makeItem(id: "abc")).id,
            DeepLinkDestination.play(makeItem(id: "def")).id
        )
    }

    func testDestinationIdStableForSameItemAndAction() {
        let item = makeItem(id: "abc123")
        XCTAssertEqual(DeepLinkDestination.detail(item).id, DeepLinkDestination.detail(item).id)
    }
}
