import Foundation

/// Parsed representation of a `sashimi://` URL, as generated by the Top Shelf
/// extension (see `TopShelf/ContentProvider.swift`):
/// - `sashimi://play/{id}` — start playback of the item
/// - `sashimi://item/{id}` — show the item's detail view
struct DeepLink: Equatable {
    enum Action: String {
        case play
        case item
    }

    let action: Action
    let itemId: String

    init?(url: URL) {
        guard url.scheme?.lowercased() == "sashimi",
              let host = url.host?.lowercased(),
              let action = Action(rawValue: host) else {
            return nil
        }

        // First real path component is the Jellyfin item id
        guard let itemId = url.pathComponents.first(where: { $0 != "/" }), !itemId.isEmpty else {
            return nil
        }

        self.action = action
        self.itemId = itemId
    }
}

/// Resolved presentation target for a deep link. A single enum driving one
/// `fullScreenCover(item:)` — rather than sibling covers per action —
/// guarantees a second link can always replace whatever is on screen.
enum DeepLinkDestination: Identifiable, Equatable {
    case play(BaseItemDto)
    case detail(BaseItemDto)

    /// Includes the action so switching play <-> detail for the *same* item
    /// still changes identity and re-presents the cover.
    var id: String {
        switch self {
        case .play(let item): return "play-\(item.id)"
        case .detail(let item): return "detail-\(item.id)"
        }
    }
}
